version: '3'

services: 

    postgres: 
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=123
        ports: 
            - '5432:5432'
        volumes: 
            - ./database:/var/lib/postgresql/data
    server: 
        build: ./server
        ports: 
            - '3000:3000'
        restart: on-failure
        volumes: 
        - /app/node_modules
        - ./server:/app
    
        environment: 
            - PGUSERNAME=postgres
            - PGHOSTNAME=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=123
            - PGPORT=5432
        depends_on: 
            - postgres
        links: 
            - postgres
    client: 
        build: ./client
        ports: 
            - 80:80
        restart: on-failure
        links: 
            - server
        depends_on: 
            - server
        
